
default:
  tags:
    - shared-fi
  image: node

build-frontend:
  script: 
    - echo "Start building App"
    - cd frontend
    - npm install
    - npm run build
    - echo "Build successfully!"
  artifacts:
    expire_in: 1 hour
    paths:
      - build
      - node_modules/


lint-backend:
  script:
   - cd backend
   - npm ci --cache /npm/npm-cache --no-audit --prefer-offline
   - npx eslint --max-warnings 0 src/**/*.ts

lint-frontend:
  script:
   - cd frontend
   - npm ci --cache /npm/npm-cache --no-audit --prefer-offline
   - npx eslint --max-warnings 0 src/**/*.{ts,tsx}


format-check-frontend:
  script:
   - cd frontend
   - npm ci --cache /npm/npm-cache --no-audit --prefer-offline
   - npx prettier --check src/**/*.{ts,tsx}
  
format-check-backend:
  script:
   - cd backend
   - npm ci --cache /npm/npm-cache --no-audit --prefer-offline
   - npx prettier --check src/**/*.ts


typecheck-backend:
  script:
   - cd backend
   - npm ci --cache /npm/npm-cache --no-audit --prefer-offline
   - npx tsc --noEmit