deploy:
  tags:
    - shared-fi
  image: kroniak/ssh-client
  before_script:
    - echo "deploying app"
  script:
    - curl --silent "https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer" | bash

    - chmod 400 .secure_files/key.pem
    - ssh -o StrictHostKeyChecking=no -i .secure_files/key.pem $PROD_SERVER_USER@$PROD_SERVER_ADDRESS "cd rooms && git pull && docker compose up --build --remove-orphans"

