deploy:
  tags:
    - shared-fi
  before_script:
    - echo "deploying app"
  script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'

    - eval $(ssh-agent -s)

    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > key.pem

    - chmod 400 key.pem
    - ssh -o StrictHostKeyChecking=no -i key.pem $PROD_SERVER_USER@$PROD_SERVER_ADDRESS "cd rooms && git pull && docker compose up --build --remove-orphans"

