version: '3.8'
services:
  db:
      image: postgres:15
      restart: always
      environment:
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        POSTGRES_USER: ${DB_USER}
        POSTGRES_DB: ${DB_NAME}
      ports:
        - ${DB_PORT}:5432
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 1s
        timeout: 3s
        retries: 30
  app-backend:
    build:
      dockerfile: backend/Dockerfile
    restart: always
    ports:
      - 4000:4000
    environment:
        - DB_HOST=${DB_HOST}
        - DB_USER=${DB_USER}
        - DB_PASSWORD=${DB_PASSWORD}
        - DB_NAME=${DB_NAME}
        - DB_PORT=${DB_PORT}
        - DATABASE_URL=${DATABASE_URL}

  app-frontend:
    build:
      dockerfile: frontend/Dockerfile
    restart: always
    ports:
      - 4173:4173